server:
  port: 9001

spring:
  application:
    name: FLIGHT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flight_db?serverTimezone=UTC
    username: root
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  spring:
    graphql:
      graphiql:
        enabled: true

grpc:
  server:
    port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/