server:
  port: 8089

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        # مسار خدمة الطيران
        - id: flight-service
          uri: lb://FLIGHTSERVICE
          predicates:
            - Path=/flights/**

        # مسار خدمة الحجوزات
        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/bookings/**

        # مسار خدمة الزبائن
        - id: customer-service
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customers/**

        # مسار خدمة الدفع
        - id: payment-service
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payments/**

        # مسار خدمة الإشعارات
        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notifications/**

# ربط الجيتواي باليوريكا
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/